### ISSUE TITLE
V2 databases

### ISSUE THREAD

**Issue by Motko222** [scotopic/silo-wallet#20]
Forks that are using V2 databases are not working with silo-wallet:

ERROR: blockchain path does not exist:  /root/.bpx/mainnet/db/blockchain_v1_mainnet.sqlite

Example forks:
BPX
SHIBGREEN
CACTUS
LITTLELAMBOCOIN

Thanks!

**Comment by scotopic** [comment]
Yup, almost ready in https://github.com/scotopic/silo-wallet/pull/21

**Comment by Motko222** [comment]
works like a charm, thanks!
