### ISSUE TITLE
Not experienced

### ISSUE THREAD

**Issue by glukkon24** [scotopic/silo-wallet#4]
I am not experienced in Linux and have no clue how to run.

**Comment by glukkon24** [comment]
Ok I figured out how to run it but it comes back as blockchain does not exist apparently it is pulling wrong directory it comes up with one name but the directory where the .files are is not the one it is pulling

**Comment by glukkon24** [comment]
How do you change the path?

**Comment by scotopic** [comment]
1. What OS/distribution + OS/distro version are you on? ( e.g. Ubuntu 20.04 LTS )
2. What is your home path? ( e.g. `/home/<myuser/` )
3. What fork are you testing on? ( e.g. `chia` )

**Comment by scotopic** [comment]
Closing since I haven't gotten a response in 28 days.
